# Timezones
Timezone.create([
  { name: 'Pacific/Midway', offset: '-11:00' },
  { name: 'Pacific/Honolulu', offset: '-10:00' },
  { name: 'America/Anchorage', offset: '-9:00' },
  { name: 'America/Los_Angeles', offset: '-8:00' },
  { name: 'America/Denver', offset: '-7:00' },
  { name: 'America/Chicago', offset: '-6:00' },
  { name: 'America/New_York', offset: '-5:00' },
  { name: 'America/Halifax', offset: '-4:00' },
  { name: 'America/Godthab', offset: '-3:00' },
  { name: 'Atlantic/Azores', offset: '-1:00' },
  { name: 'Europe/London', offset: '0:00' },
  { name: 'Europe/Berlin', offset: '+1:00' },
  { name: 'Europe/Athens', offset: '+2:00' },
  { name: 'Europe/Moscow', offset: '+3:00' },
  { name: 'Asia/Dubai', offset: '+4:00' },
  { name: 'Asia/Kabul', offset: '+4:30' },
  { name: 'Asia/Karachi', offset: '+5:00' },
  { name: 'Asia/Kolkata', offset: '+5:30' },
  { name: 'Asia/Kathmandu', offset: '+5:45' },
  { name: 'Asia/Dhaka', offset: '+6:00' },
  { name: 'Asia/Rangoon', offset: '+6:30' },
  { name: 'Asia/Bangkok', offset: '+7:00' },
  { name: 'Asia/Singapore', offset: '+8:00' },
  { name: 'Asia/Tokyo', offset: '+9:00' },
  { name: 'Australia/Sydney', offset: '+10:00' },
  { name: 'Pacific/Noumea', offset: '+11:00' },
  { name: 'Pacific/Auckland', offset: '+12:00' }
])
